/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginGUI.h"


//==============================================================================
PluginComponentGuiAudioProcessor::PluginComponentGuiAudioProcessor()
{
}

PluginComponentGuiAudioProcessor::~PluginComponentGuiAudioProcessor()
{
}

//==============================================================================
const String PluginComponentGuiAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int PluginComponentGuiAudioProcessor::getNumParameters()
{
    return NUM_PARAMS;
}

float PluginComponentGuiAudioProcessor::getParameter (int index)
{
    float value = 0.0f;
    switch(index) {
        case MODFREQUENCY:
            value = modFrequency;
        break;
    }
    return value;
}

void PluginComponentGuiAudioProcessor::setParameter (int index, float newValue)
{
    switch(index) {
        case MODFREQUENCY:
            modFrequency = newValue;
        break;
    }
}

const String PluginComponentGuiAudioProcessor::getParameterName (int index)
{
    String name = "";
    switch(index) {
        case MODFREQUENCY:
            name = "Modulation frequency";
        break;
    }
    return name;
}

const String PluginComponentGuiAudioProcessor::getParameterText (int index)
{
    String name = "";
    switch(index) {
        case MODFREQUENCY:
            name = "Modulation frequency";
        break;
    }
    return name;
}

const String PluginComponentGuiAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String PluginComponentGuiAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool PluginComponentGuiAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool PluginComponentGuiAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool PluginComponentGuiAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool PluginComponentGuiAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool PluginComponentGuiAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double PluginComponentGuiAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int PluginComponentGuiAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int PluginComponentGuiAudioProcessor::getCurrentProgram()
{
    return 0;
}

void PluginComponentGuiAudioProcessor::setCurrentProgram (int index)
{
}

const String PluginComponentGuiAudioProcessor::getProgramName (int index)
{
    return String();
}

void PluginComponentGuiAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void PluginComponentGuiAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void PluginComponentGuiAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void PluginComponentGuiAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i) 
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    
    float blockPhase = sineOscillator.phase();
    sineOscillator.freq(modFrequency);
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* outBuffer = buffer.getWritePointer (channel);
        const float* inBuffer = buffer.getReadPointer (channel);
        sineOscillator.phase(blockPhase);
        for (int samp = 0; samp < buffer.getNumSamples(); samp++) {
            *outBuffer++ = *inBuffer++ * sineOscillator();
        }
    }
}

//==============================================================================
bool PluginComponentGuiAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* PluginComponentGuiAudioProcessor::createEditor()
{
    return new PluginGUI (*this);
}

//==============================================================================
void PluginComponentGuiAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void PluginComponentGuiAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new PluginComponentGuiAudioProcessor();
}
